containers:
  production:
    environment: production
    build:
      command: pipa build -x --push -- ./build.sh gcr.io/shopify-docker-images/apps/production/ingress:${BUILDKITE_COMMIT}
  ci:
    environment: ci
    build:
      command: pipa build -x --push -- ./build.sh gcr.io/shopify-docker-images/apps/ci/ingress:${BUILDKITE_COMMIT}

pipelines:
  nginx-ingress-controller-ci:
    steps:
      - build: ci

  nginx-ingress-controller-production:
    steps:
      - build: production
